//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grafilogika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        public string Name { get; set; }
        public string Uploader { get; set; }
        public Nullable<int> Wins { get; set; }
        public Nullable<int> Mistakes { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Game { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
