//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grafilogika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Games = new HashSet<Games>();
        }
    
        public string Name { get; set; }
        public string Password { get; set; }
        public Nullable<int> Wins { get; set; }
        public Nullable<int> Mistakes { get; set; }
        public Nullable<int> Isadmin { get; set; }
        public string Email { get; set; }
        public int Isverified { get; set; }
    
        public virtual ICollection<Games> Games { get; set; }
    }
}
